#!/usr/bin/env bash
set -e

cd /
git clone https://github.com/AllenNeuralDynamics/comb
cd comb
pip install -e .
#git checkout 21b9cae9431f7f83e1973af6f1fc1ecd40fc765d
git checkout for_gcamp_validation
    

cd /
git clone https://github.com/AllenNeuralDynamics/lamf-analysis
cd lamf-analysis
pip install -e .    

# install libraries for opencv-python
apt-get update
apt-get install -y libxcb1 libgl1 libglib2.0-0


# install updated version of code-server
# VERSION=4.96.4
VERSION=4.109.2
mkdir /.code-server
cd /.code-server
curl -fL "https://github.com/coder/code-server/releases/download/v$VERSION/code-server-$VERSION-linux-amd64.tar.gz" \
  | tar -xz

ln -sf /.code-server/code-server-$VERSION-linux-amd64/bin/code-server  /usr/bin/code-server
cd -

# download and install vscode extension from file
# for extensions not available in the default open-vsx registry

# run from within a workstation or in postinstall
# won't work in postinstall if extensions folder has been moved to inside capsule filesystem!
download_and_install_extension() {
    publisher=$1
    name=$2
    version=$3
    file=/tmp/$publisher.$name.$version.vsix
    curl -fL http://${publisher}.gallery.vsassets.io/_apis/public/gallery/publisher/${publisher}/extension/${name}/${version}/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage \
        --output $file
    code-server --disable-telemetry --extensions-dir=/.vscode/extensions --install-extension $file
}

# # default behavior: extensions are cleared when capsule is rebuilt, can be installed in postInstall
# # alternative: install extensions manually inside capsule, and save them across rebuilds
persist_extensions_in_capsule=false

if $persist_extensions_in_capsule; then
  # move VS code extensions directory into capsule and symlink
  # (this may cause issues on the first run that will be solved by reloading VS code
  echo "mkdir -p /root/capsule/.vscode/extensions" >> /root/.profile
  ln -s /root/capsule/.vscode /.vscode
  #   install extensions from workstation
else
  mkdir -p /.vscode/extensions
  # install some default extensions (must be done manually if extensions moved inside capsule
  # these versions have working Jedi intellisense in notebooks (with setting "python.languageServer": "Jedi")
  code-server --disable-telemetry --extensions-dir=/.vscode/extensions --install-extension ms-toolsai.jupyter@2023.9.100
  code-server --disable-telemetry --extensions-dir=/.vscode/extensions --install-extension ms-python.python@2024.2.1
  #   add code to install extensions here...
  # comment out as needed:
   ## these versions should be compatible with code-server 4.93.1
   # download_and_install_extension github copilot-chat 0.20.0
   # download_and_install_extension github copilot 1.241.0
   ## for 4.95.1
   # download_and_install_extension github copilot-chat 0.22.1
   # download_and_install_extension github copilot 1.243.0
   # download_and_install_extension MS-vsliveshare vsliveshare 1.0.5900
   # for 4.96.4
   # download_and_install_extension github copilot-chat 0.23.2
   # download_and_install_extension github copilot 1.260.0
  # for 4.109.2
   download_and_install_extension github copilot-chat 0.37.5
  #  download_and_install_extension github copilot 1.260.0

fi